#!/bin/sh
# 执行eslint 样式 代码风格校验
echo "正在修复代码风格..."
npx lint-staged

echo "正在检查代码样式..."
pnpm lint:style:strict || exit 1

echo "正在检查提交信息..."
COMMIT_MSG=$(git log -1 --pretty=%B)
echo "提交信息: $COMMIT_MSG"
echo "$COMMIT_MSG" | npx --no -- commitlint